export const AIDoctorAgents = [
    {
        id: 1,
        specialist: "Kashi Sahitya",
        description: "काशी की अनुभूति, शब्दों के साथ (The experience of Kashi, through words)",
        image: "/kashisahitya1.png",
        vapiAgentId: "6ad9fdaf-225c-447d-a809-dff7e9e04ce9",
      keywords: [
      "literature",
      "poetry",
      "writers",
      "books",
      "stories",
      "novels",
      "hindi literature",
      "sanskrit",
      "manuscripts",
      "authors",
      "philosophy",
      "texts",
      "word",
      "writing",
    ],
        
    },
    {
        id: 2,
        specialist: "Kashi Heritage",
        description: "काशी की विरासत, स्मृतियों और समय में (Kashi’s heritage, in memory and time)",
        image: "/kashihertage1.png",
        vapiAgentId: "003fff2d-439a-453b-86fd-5dafc45ba9c0",
         keywords: [
      "heritage",
      "history",
      "ancient",
      "temples",
      "architecture",
      "tradition",
      "old city",
      "culture",
      "historical places",
      "civilization",
      "monuments",
      "archaeology",
      
    ]
    },
    {
        id: 3,
        specialist: "Sangeet Sarita",
        description: "संगीत की धारा में बहती काशी (Kashi flowing through the stream of music)",
        image: "/sangeetsarita.png",
        vapiAgentId: "eeac2d4e-2cb3-4147-999f-18d60ee24f4d",
       keywords: [
      "music",
      "classical music",
      "indian music",
      "ragas",
      "bhajan",
      "tabla",
      "sitar",
      "singing",
      "songs",
      "concert",
      "musicians",
      "melody",
    ],
    },
    {
        id: 4,
        specialist: "Kashi Rasoi",
        description: "स्वाद की काशी, परंपरा और पोषण में (Kashi of flavors, in tradition and nutrition)",
        image: "/kashirasoi.png",
        vapiAgentId: "8b6f660e-f073-41c0-b08f-0ad0726e216f",
       keywords: [
      "food",
      "banarasi food",
      "street food",
      "cuisine",
      "indian food",
      "local food",
      "sweets",
      "malaiyo",
      "kachori",
      "chaat",
      "breakfast",
      "eating",
    ],
    },
    {
        id: 5,
        specialist: "Moksha Kashi",
        description: "मोक्ष की ओर ले जाती काशी (Kashi that leads to liberation)",
        image: "/mokshakashi1.png",
        vapiAgentId: "5bfc1115-af80-4028-9286-a2ddfbee5db7",
         keywords: [
      "moksha",
      "liberation",
      "death",
      "afterlife",
      "spirituality",
      "salvation",
      "manikarnika",
      "cremation",
      "life and death",
      "rituals",
      "spiritual journey",
    ],
        
    },
   
    {
        id: 6,
        specialist: "Kashi Weaves",
        description: "करघों में बुनी काशी (Kashi woven in the threads of tradition).",
        image: "/kashiweaves.png",
        vapiAgentId: "56cfdcf5-333d-4cf0-96cc-17732b4b062c",
         keywords: [
      "saree",
      "banarasi saree",
      "silk",
      "weaving",
      "textiles",
      "handloom",
      "fashion",
      "traditional dress",
      "attire",
      "clothing",
      "fabric",
    ],
    },
    {
        id: 7,
        specialist: "Bauddha Kashi",
        description: "बुद्धत्व की शांति में काशी (Kashi in the peace of Buddhahood)",
        image: "/bauddhakashi.png",
        vapiAgentId: "232419ae-3f60-4ce2-9d79-f19faa28349c",
        keywords: [
      "buddhism",
      "buddha",
      "sarnath",
      "meditation",
      "monks",
      "peace",
      "dharma",
      "buddhist",
      "enlightenment",
      "stupa",
    ],
    },
    {
        id: 8,
        specialist: "Ganga Mahima",
        description: "गंगा की गोद में काशी (Kashi in the embrace of the Ganga)",
        image: "/gangamahima.png",
        vapiAgentId: "4161ccf9-0124-4dc4-8b86-06185fa0a83d",
         keywords: [
      "ganga",
      "river",
      "holy river",
      "aarti",
      "water",
      "boat ride",
      "river rituals",
      "evening aarti",
      "spiritual river",
    ],
    },
    {
        id: 9,
        specialist: "Ghat Darshan",
        description: "हर घाट, एक कहानी (Every ghat, a story)",
        image: "/ghatdarshan.png",
        vapiAgentId: "7a094ef5-2f3b-4b3a-bfe8-4d8e28b59a05",
         keywords: [
      "ghat",
      "ghats",
      "riverfront",
      "steps",
      "boats",
      "sunrise",
      "sunset",
      "ritual bathing",
      "photography",
      "river view",
    ],


    },
    {
        id: 10,
        specialist: "Nayi Kashi",
        description: "परंपरा से भविष्य की ओर बढ़ती काशी (Kashi moving from tradition to the future)",
        image: "/nayikashi.png",
        vapiAgentId: "4add7824-e4ec-4c14-b75e-bdfff89295a1",
         keywords: [
      "modern",
      "development",
      "new city",
      "future",
      "technology",
      "infrastructure",
      "urban",
      "growth",
      "smart city",
      "education",
    ],
    },
];
