import React from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SessionDetail } from "../medical-agent/[sessionId]/page";
import moment from "moment";

type props = {
  record: SessionDetail;
};

function ViewReportDialog({ record }: props) {
  const report: any = record?.report;
  const formatDate = moment(record?.createdOn).format(
    "MMMM Do YYYY, h:mm a"
  );

  if (!report) return null;

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="link" size="sm">
          View
        </Button>
      </DialogTrigger>

      <DialogContent className="max-h-[90vh] overflow-y-auto bg-white shadow-lg p-6 border w-[750px]">
        <DialogHeader>
          <DialogTitle asChild>
            <h2 className="text-center text-3xl font-bold text-orange-600 mb-2">
              🌸Kashivani Cultural Conversation Report🌸
            </h2>
          </DialogTitle>

          <DialogDescription asChild>
            <div className="space-y-6 text-gray-800 text-sm">

              {/* 🪔 Session Overview */}
              <div>
                <h3 className="text-lg font-semibold text-orange-600">
                  Session Overview
                </h3>
                <hr className="border-t-2 border-orange-500 my-2" />
                <div className="grid grid-cols-2 gap-3">
                  <p><strong>Agent:</strong> {report.agent}</p>
                  <p><strong>Theme:</strong> {report.theme}</p>
                  <p><strong>User:</strong> {report.user}</p>
                  <p><strong>Explored On:</strong> {formatDate}</p>
                </div>
              </div>

              {/* ❓ Key Concerns */}
              {report.keyConcerns?.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold text-orange-600">
                    Key Concerns Raised
                  </h3>
                  <hr className="border-t-2 border-orange-500 my-2" />
                  <ul className="list-disc list-inside">
                    {report.keyConcerns.map((q: string, i: number) => (
                      <li key={i}>{q}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* 💬 Key Responses */}
              {report.keyResponses?.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold text-orange-600">
                    Key Responses & Narratives
                  </h3>
                  <hr className="border-t-2 border-orange-500 my-2" />
                  <ul className="list-disc list-inside">
                    {report.keyResponses.map((res: string, i: number) => (
                      <li key={i}>{res}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* 📜 Summary */}
              <div>
                <h3 className="text-lg font-semibold text-orange-600">
                  Cultural Summary
                </h3>
                <hr className="border-t-2 border-orange-500 my-2" />
                <p>{report.summary}</p>
              </div>

              {/* 🕉️ Cultural References */}
              {report.culturalReferences?.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold text-orange-600">
                    Cultural References
                  </h3>
                  <hr className="border-t-2 border-orange-500 my-2" />
                  <ul className="list-disc list-inside">
                    {report.culturalReferences.map((ref: string, i: number) => (
                      <li key={i}>{ref}</li>
                    ))}
                  </ul>
                </div>
              )}

              {/* 🌿 Suggested Explorations */}
              {report.suggestedExplorations?.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold text-orange-600">
                    Suggested Explorations
                  </h3>
                  <hr className="border-t-2 border-orange-500 my-2" />
                  <ul className="list-disc list-inside">
                    {report.suggestedExplorations.map(
                      (item: string, i: number) => (
                        <li key={i}>{item}</li>
                      )
                    )}
                  </ul>
                </div>
              )}

              {/* 🌺 Footer */}
              <div className="pt-6 border-t text-center text-xs text-gray-500">
                This conversational report was generated by Kashivani —  
                capturing the living dialogue of Kashi.
              </div>
            </div>
          </DialogDescription>
        </DialogHeader>
      </DialogContent>
    </Dialog>
  );
}

export default ViewReportDialog;
